### ISSUE TITLE
[Todo] Can use color.mix function to generate 950 color shades

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo#242]
So right now we use the Tailwind color palette which is pretty good, but it would be nice if we have support for 950 colors. That number represents the shade. So the lightest shade is -50 and the heaviest (before black) is 900. It would be nice if we can have both -50 and -950. In the past I’ve needed to use a -950 shade but had to mix 900 and black myself.

So this involves opening the `configuration/colors.scss` and doing something like this:

```scss
	// ...
	light-blue-800: #075985,
	light-blue-900: #0c4a6e,
	light-blue-950: color.mix(#0c4a6e, #000),
	cyan-50: #ecfeff,
	cyan-100: #cffafe,
	// ...
```

If you want, you can also do something like this:

```scss
$color-map: (
	// ...
);
map.set($color-map, light-blue-950, color.mix(map.get($color-map, $light-blue-900), #000);
// ...
```

Just make sure you do it for both the `$color-map` and `$subset-color-map`. The `$subset-color-map` can probably just do:

```scss
	// ...
	amber-950: map.get($color-map, amber-950),
	// ...
```

I found this function from the Sass library: https://sass-lang.com/documentation/modules/color#mix, so you can do `@use "sass:color";` at the top of the `configuration/colors.scss` file to get access to `color.mix`.

**Comment by zaydek** [comment]
Never mind, we can’t encode background-opacity into RGBA color spaces.

**Comment by zaydek** [comment]
_Still need to document this for you._

**Comment by joyact** [comment]
Done.
